In [1]:
import numpy as np

In [2]:
lista = [1,2,3]

In [4]:
np.array(lista)

array([1, 2, 3])

In [5]:
print(np.array(lista))

[1 2 3]


In [6]:
arreglo = np.array(lista)

In [8]:
arreglo.dtype

dtype('int32')

In [9]:
arreglo[0]

1

## Ejercicio: Sumar dos listas

In [11]:
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [13]:
arreglo

array([1, 2, 3])

In [12]:
arreglo + arreglo

array([2, 4, 6])

In [14]:
arreglo2 = [10,20,30,40]

## Ejercicio: Obtener una lista que contenga los números al cuadrado de 1 al 10

In [16]:
lista_vacia = []
for i in range (1,11):
    lista_vacia.append(i**2)
lista_vacia

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [17]:
[x**2 for x in range(1,11)]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [18]:
np.arange(1,11)**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [20]:
np.array(arreglo2) +150

array([160, 170, 180, 190])

In [21]:
lista = [1, 2, 3]
np.array(lista)

array([1, 2, 3])

In [22]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Calcular el IMC

In [23]:
peso = [80.4, 74.5, 99.5, 75.9, 105.5]

In [24]:
estatura = [1.80, 1.65, 1.72, 1.63, 1.80]

In [25]:
imc = []
for i in range(len(peso)):
    imc.append(peso[i]/estatura[i]**2)

imc

[24.814814814814817,
 27.364554637281913,
 33.63304488912926,
 28.567127103014794,
 32.56172839506173]

In [28]:
imc = np.array(peso) / np.array(estatura)**2
imc

array([24.81481481, 27.36455464, 33.63304489, 28.5671271 , 32.5617284 ])

$$imc = \frac{peso}{estatura^2}

In [29]:
ejemplo = np.array([1, 2, 3, "5"])
ejemplo

array(['1', '2', '3', '5'], dtype='<U11')

Condicionales

In [30]:
15 < 20

True

In [31]:
arreglo

array([1, 2, 3])

In [32]:
imc

array([24.81481481, 27.36455464, 33.63304489, 28.5671271 , 32.5617284 ])

In [33]:
imc > 30

array([False, False,  True, False,  True])

Filtro

In [34]:
imc[imc > 30]

array([33.63304489, 32.5617284 ])

In [35]:
list(imc[imc > 30])

[33.63304488912926, 32.56172839506173]

## Crear arrays

In [36]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [38]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [39]:
np.arange(15,31)

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [41]:
np.arange(10, 31, 5)

array([10, 15, 20, 25, 30])

Linspace

In [42]:
np.linspace(1, 2, 5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [43]:
np.linspace(0,100,4)

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [44]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [47]:
np.linspace(-5, 5, 11)

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

Random

In [49]:
np.random.randint(10)

0

In [50]:
np.random.randint(50,100)

92

In [51]:
np.random.randint(50,100,10)

array([95, 80, 58, 61, 61, 74, 91, 77, 88, 62])

In [52]:
np.random.rand(10)

array([0.79245666, 0.82545044, 0.34314117, 0.65209431, 0.087284  ,
       0.77716773, 0.41285938, 0.92149156, 0.83316434, 0.31932851])

In [53]:
numeros_aleatorios = np.random.randint(10,20,10)
numeros_aleatorios.sort()
numeros_aleatorios

array([11, 12, 13, 13, 13, 14, 15, 18, 19, 19])

In [ ]:
.mean()

## Matrices

In [71]:
sublista = [ [1.80, 83.4], [1.76, 80.5], [1.78, 82.5] ]

In [72]:
matriz = np.array(sublista)
matriz

array([[ 1.8 , 83.4 ],
       [ 1.76, 80.5 ],
       [ 1.78, 82.5 ]])

In [73]:
matriz[:, 0]

array([1.8 , 1.76, 1.78])

In [74]:
matriz.shape

(3, 2)

In [75]:
matriz[0, :]

array([ 1.8, 83.4])

In [77]:
matriz[1:, :]

array([[ 1.76, 80.5 ],
       [ 1.78, 82.5 ]])

In [80]:
matriz[[0,2],:]

array([[ 1.8 , 83.4 ],
       [ 1.78, 82.5 ]])

In [82]:
matriz

array([[ 1.8 , 83.4 ],
       [ 1.76, 80.5 ],
       [ 1.78, 82.5 ]])

In [81]:
np.where(matriz > 1.79)

(array([0, 0, 1, 2], dtype=int64), array([0, 1, 1, 1], dtype=int64))

In [83]:
filas, columnas = np.where(matriz > 1.79)

In [84]:
filas

array([0, 0, 1, 2], dtype=int64)

In [85]:
columnas

array([0, 1, 1, 1], dtype=int64)

In [88]:
for fila, columna in zip(filas, columnas):
    print(f'{fila} {columna} {matriz[fila][columna]}')

0 0 1.8
0 1 83.4
1 1 80.5
2 1 82.5


In [89]:
import pandas as pd

In [90]:
data = pd.read_csv('https://assets.datacamp.com/production/repositories/288/datasets/026a5211b906ac118a09b1a0dbf7df48faafb379/fifa.csv')

In [91]:
data

id                     name   rating  position   height    foot  \
0       1001             Gábor Király       69        GK      191   Right   
1     100143             Frederik Boi       65         M      184   Right   
2     100264          Tomasz Szewczuk       57         A      185   Right   
3     100325   Steeve Joseph-Reinette       63         D      180    Left   
4     100326             Kamel Chafni       72         M      181   Right   
...      ...                      ...      ...       ...      ...     ...   
8842    9801          Danijel Ljuboja       73         A      189    Left   
8843    9805            Craig Bellamy       79         A      175   Right   
8844    9807            Michel Breuer       68         D      183   Right   
8845    9815              Gill Swerts       65         D      179   Right   
8846    9913              Mehdi Nafti       69         M      179   Right   

       rare  pace  shooting  passing  dribbling  defending  heading  diving  \
0         0                                                              70   
1         0    61        65       63         59         62       62           
2         0    65        54       43         53         55       74           
3         0    68        38       51         46         64       71           
4         0    75        64       67         72         57       66           
...     ...   ...       ...      ...        ...        ...      ...     ...   
8842      1    62        73       64         74         56       68           
8843      0    80        78       67         81         62       71           
8844      0    61        40       56         51         70       74           
8845      0    65        48       63         65         67       69           
8846      0    55        56       64         65         69       60           

      handling  kicking  reflexes  speed   positioning  
0           66       63        74     35          66.0  
1                                                  NaN  
2                                                  NaN  
3                                                  NaN  
4                                                  NaN  
...        ...      ...       ...    ...           ...  
8842                                               NaN  
8843                                               NaN  
8844                                               NaN  
8845                                               NaN  
8846                                               NaN  

[8847 rows x 19 columns]

In [92]:
data.columns

Index(['id', ' name', ' rating', ' position', ' height', ' foot', ' rare',
       ' pace', ' shooting', ' passing', ' dribbling', ' defending',
       ' heading', ' diving', ' handling', ' kicking', ' reflexes', ' speed',
       ' positioning'],
      dtype='object')

In [94]:
data[' name']

0                  Gábor Király
1                  Frederik Boi
2               Tomasz Szewczuk
3        Steeve Joseph-Reinette
4                  Kamel Chafni
                 ...           
8842            Danijel Ljuboja
8843              Craig Bellamy
8844              Michel Breuer
8845                Gill Swerts
8846                Mehdi Nafti
Name:  name, Length: 8847, dtype: object

In [96]:
data[' name'].values

array([' Gábor Király', ' Frederik Boi', ' Tomasz Szewczuk', ...,
       ' Michel Breuer', ' Gill Swerts', ' Mehdi Nafti'], dtype=object)

In [97]:
positions = data[' position'].values
positions

array([' GK', ' M', ' A', ..., ' D', ' D', ' M'], dtype=object)

In [99]:
heights = data[' height'].values
heights

array([191, 184, 185, ..., 183, 179, 179], dtype=int64)

In [104]:
positions == ' GK'

array([ True, False, False, ..., False, False, False])

In [105]:
positions[positions == ' GK']

array([' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK',
       ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK',
       ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK',
       ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK',
       ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK',
       ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK',
       ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK',
       ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK',
       ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK',
       ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK',
       ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK',
       ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK',
       ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK',
       ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK', ' GK',
       ' GK', ' GK',

In [109]:
hgk = heights[positions == ' GK']
hgk

array([191, 193, 190, 185, 188, 187, 189, 196, 190, 189, 188, 189, 188,
       188, 190, 193, 181, 191, 193, 190, 183, 183, 193, 193, 196, 184,
       190, 186, 195, 191, 187, 185, 186, 185, 186, 190, 185, 185, 187,
       188, 188, 186, 187, 193, 183, 185, 190, 186, 182, 191, 194, 191,
       194, 188, 185, 189, 187, 188, 184, 176, 187, 186, 191, 188, 191,
       192, 190, 188, 189, 184, 180, 191, 197, 189, 185, 191, 190, 190,
       185, 186, 186, 189, 193, 182, 189, 188, 190, 191, 183, 189, 189,
       190, 188, 184, 194, 188, 194, 193, 186, 186, 188, 187, 191, 192,
       196, 187, 187, 187, 192, 184, 189, 184, 185, 187, 202, 190, 185,
       182, 188, 188, 195, 187, 183, 197, 188, 190, 193, 191, 187, 184,
       183, 185, 193, 180, 191, 185, 188, 188, 186, 188, 188, 184, 186,
       189, 193, 194, 183, 178, 184, 190, 183, 184, 188, 194, 190, 183,
       194, 188, 180, 173, 187, 183, 184, 193, 188, 183, 190, 191, 199,
       186, 198, 188, 189, 189, 185, 193, 191, 188, 185, 185, 18

In [108]:
hgk.mean()

188.23333333333332